services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - myNetwork
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: miansahin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - myNetwork
    restart: unless-stopped

  job-service:
    image: donsaifulban1/jobms
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobms
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobmsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - myNetwork
    restart: unless-stopped

  company-service:
    image: donsaifulban1/companyms
    build:
      context: ../companyms
      dockerfile: Dockerfile
    container_name: companyms
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/companymsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - myNetwork
    restart: unless-stopped

  review-service:
    image: donsaifulban1/reviewms
    build:
      context: ../reviewms
      dockerfile: Dockerfile
    container_name: reviewms
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reviewmsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8083:8083"
    networks:
      - myNetwork
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:


networks:
  myNetwork:
