services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - myNetwork
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: miansahin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - myNetwork
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - myNetwork
    restart: always

  job-service:
    image: donsaifulban1/jobms
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobms
    depends_on:
      - postgres
      - config-server
      - service-registry
      - zipkin
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jobmsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - "8080:8080"
    networks:
      - myNetwork
    restart: unless-stopped

  company-service:
    image: donsaifulban1/companyms
    build:
      context: ../companyms
      dockerfile: Dockerfile
    container_name: companyms
    depends_on:
      - postgres
      - rabbitmq
      - config-server
      - service-registry
      - zipkin
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/companymsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - "8081:8081"
    networks:
      - myNetwork
    restart: unless-stopped

  review-service:
    image: donsaifulban1/reviewms
    build:
      context: ../reviewms
      dockerfile: Dockerfile
    container_name: reviewms
    depends_on:
      - postgres
      - config-server
      - service-registry
      - zipkin
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reviewmsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    ports:
      - "8083:8083"
    networks:
      - myNetwork
    restart: unless-stopped

  config-server:
    image: donsaifulban1/config-server
    build:
      context: ../config-server
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - myNetwork
    restart: unless-stopped

  service-registry:
    image: donsaifulban1/service-registry
    build:
      context: ../service-registry
      dockerfile: Dockerfile
    container_name: service-registry
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888/"
    networks:
      - myNetwork
    restart: unless-stopped

  gateway:
    image: donsaifulban1/gateway
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8084:8084"
    depends_on:
      - config-server
      - service-registry
      - zipkin
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - myNetwork
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - myNetwork
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:


networks:
  myNetwork:
